# fly.toml app configuration file generated for shopping-memo on 2023-12-24T12:36:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopping-memo"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
